config/routes.rb
Rails.application.routes.draw do
  resources :investments do
    get 'csv_export', on: :collection
    get 'json_export', on: :collection
  end
  resources :cryptocoins
  get '/update_annual_balance_usd_value', to: 'investments#update_annual_balance_usd_value'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "investments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cryptocoin.rb
class Cryptocoin < ApplicationRecord
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :cryptocoins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/investments_controller.rb
require 'csv'

class InvestmentsController < ApplicationController
  include HTTParty

  before_action :set_investment, only: %i[ show edit update destroy ]

  base_uri 'https://rest.coinapi.io/v1'


  def getCoinSymbol(coin)
    if coin == "Bitcoin"
      return "BTC"
    elsif coin == "Ether"
      return "ETH"
    elsif coin == "Cardano"
      return "ADA"
    else
      return "Other"
    end
  end


  def get_cryptocoin_info()
    table_info = CSV.parse(File.read("app/assets/files/origen.csv"), headers: true)
    cryptocoin_info = []
  
    table_info.each do |row|
      monthly_return = row["Interes_mensual"].to_f / 100.0
      initial_balance = row["balance_ini"].to_f
      annual_balance = calculate_annual_return(monthly_return, initial_balance)
      price_usd = get_coin_price(row["Moneda"])
      annual_balance_usd = price_usd.present? ? "USD #{(annual_balance * price_usd).round(2)}" : "No se pudo obtener el valor"
  
      cryptocoin_info << {
        name: row["Moneda"],
        initial_balance: "#{getCoinSymbol(row["Moneda"])} #{initial_balance}",
        monthly_return: "#{row["Interes_mensual"]} %",
        annual_balance: "#{getCoinSymbol(row["Moneda"])} #{annual_balance.round(2) if annual_balance}",
        annual_balance_usd: annual_balance_usd,
      }
    end

    cryptocoin_info
  end


  def get_coin_price(coin)
    access_token = Rails.application.credentials.dig(:coin_api_access_token)
    headers = {
      'X-CoinAPI-Key' => access_token
    }
    coin_symbol = getCoinSymbol(coin)
    response = self.class.get("/exchangerate/#{coin_symbol}/USD", headers: headers)
    
    if response.success?
      price_data = JSON.parse(response.body)
      return price_data["rate"]
    else
      return nil
    end
  end


  def calculate_annual_return(monthly_return, initial_balance)
    annual_return = initial_balance
    12.times do
      annual_return *= (1 + monthly_return)
    end
    annual_return
  end


  def update_annual_balance_usd_value   
    @cryptocoin_info = get_cryptocoin_info
    annual_balance_usd = ""
    @cryptocoin_info.each do |row|
      annual_balance_usd = row[:annual_balance_usd]
    end
       
    respond_to do |format|
      format.json { render json: { annual_balance_usd: annual_balance_usd } }
    end
  end
  


  def csv_export
    @cryptocoin_info = get_cryptocoin_info
    data = @cryptocoin_info.map do |info|
      [
        info[:name] || "", 
        info[:initial_balance] || "", 
        info[:monthly_return] || "", 
        info[:annual_balance] || "", 
        info[:annual_balance_usd] || ""
      ]
    end
  
    csv_data = CSV.generate(headers: true) do |csv|
      csv << ["Moneda", "Balance Inicial", "Retorno Mensual", "Balance Anual Proyectado", "Balance Anual Proyectado en USD"]
      data.each { |row| csv << row }
    end
  
    send_data csv_data, filename: "investments.csv"
  
  end
  

  def json_export
    @cryptocoin_info = get_cryptocoin_info
    json_data = @cryptocoin_info.to_json

    respond_to do |format|
      format.json { send_data json_data, filename: "investments.json" }
    end
  end
  

  # GET /investments or /investments.json
  def index
    @cryptocoin_info = get_cryptocoin_info
  end

  # GET /investments/1 or /investments/1.json
  def show
  end

  # GET /investments/new
  def new
    @investment = Investment.new
  end

  # GET /investments/1/edit
  def edit
  end

  # POST /investments or /investments.json
  def create
    @investment = Investment.new(investment_params)

    respond_to do |format|
      if @investment.save
        format.html { redirect_to investment_url(@investment), notice: "Investment was successfully created." }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1 or /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to investment_url(@investment), notice: "Investment was successfully updated." }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1 or /investments/1.json
  def destroy
    @investment.destroy!

    respond_to do |format|
      format.html { redirect_to investments_url, notice: "Investment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def investment_params
      params.require(:investment).permit(:price, :cryptocoins_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_form.html.erb
<%= form_with(model: investment) do |form| %>
  <% if investment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
        <% investment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cryptocoins_id, style: "display: block" %>
    <%= form.select :cryptocoins_id, options_for_select(Cryptocoin.all.map{|c|[c.name, c.id]}) %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/investments/_investment.html.erb
<div id="<%= dom_id investment %>">
  <p>
    <strong>Price:</strong>
    <%= investment.price %>
  </p>

  <p>
    <strong>Cryptocoins:</strong>
    <%= investment.cryptocoins_id %>
  </p>

</div>

app/views/investments/index.html.erb
<p class="notice"><%= notice %></p>

<h1>Calculadora de Inversiones</h1>
<span class="last-update-time"></span>
<br>

<br>
<div class="table-container">
  <table>
    <thead>
      <tr>
        <th>Moneda</th>
        <th>Balance Inicial</th>
        <th>Retorno Mensual</th>
        <th>Balance Anual Proyectado</th>
        <th>Balance Anual Proyectado en USD</th>
      </tr>
    </thead>
    <tbody>
      <% @cryptocoin_info.each do |info| %>
        <tr>
          <td class="coin-cell">
            <%= image_tag "coins/#{info[:name].downcase}.png", class: "coin-image" %>
            <%= info[:name] %>
          </td>
          <td><%= info[:initial_balance] %></td>
          <td><%= info[:monthly_return] %></td>
          <td><%= info[:annual_balance] %></td>
          <td id="annual_balance_usd_cell"><%= info[:annual_balance_usd] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="button-container">
  <%= button_to "Exportar a CSV", csv_export_investments_path(format: :csv), method: :get, class: "btn btn-primary" %>
  <%= button_to "Exportar a JSON", json_export_investments_path(format: :json), method: :get, class: "btn btn-primary" %>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    function updateAnnualBalanceValue() {
      $.ajax({
        url: '/update_annual_balance_usd_value',
        type: 'GET',
        dataType: 'json',
        success: function(response) {
          $('#annual_balance_usd_cell').text(response.annual_balance_usd);
          $('.last-update-time').text('Última actualización: ' + getCurrentTime());
        },
        error: function(error) {
          console.error('Error al obtener el valor del balance en USD:', error);
        }
      });
    }
    function getCurrentTime() {
      var now = new Date();
      var hour = now.getHours();
      var minutes = now.getMinutes();
      var seconds = now.getSeconds();
      return hour + ':' + minutes + ':' + seconds;
    }
    updateAnnualBalanceValue();
    setInterval(updateAnnualBalanceValue, 3000);
  });
</script>

app/views/investments/new.html.erb
<h1>New investment</h1>

<%= render "form", investment: @investment %>

<br>

<div>
  <%= link_to "Back to investments", investments_path %>
</div>

app/views/investments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @investment %>

<div>
  <%= link_to "Edit this investment", edit_investment_path(@investment) %> |
  <%= link_to "Back to investments", investments_path %>

  <%= button_to "Destroy this investment", @investment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvestmentWebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>